# Generated by Django 5.0.6 on 2024-11-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_user_json_data_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Helsinki', max_length=128),
            preserve_default=False,
        ),
    ]
